### ISSUE TITLE
Code published on Mautic Github

### ISSUE THREAD

**Issue by froger** [mautic/Community-Portal#26]
My actions: 
- [x] The code should be available on github
- [x] Github actions to release docker images
- [x] Bind used images in infra to the one released by dockerhub

**Comment by RCheesley** [comment]
I've set it up on [Dockerhub](https://hub.docker.com/r/mautic/community-portal) now and set up auto-builds with these settings - LMK if it needs tweaking!

![screenshot-hub docker com-2023 10 25-12_32_33](https://github.com/mautic/Community-Portal/assets/2930593/e26a9218-6b0d-4aaa-8c9a-a8f7cacaadff)

**Comment by RCheesley** [comment]
@froger I've made you an admin on the repo and @rsdeus is a maintainer so you should be able to set up any automation wizardry that might be needed 🧙 🪄 ✨
