### ISSUE TITLE
Meetings > registrations > registration form = server error

### ISSUE THREAD

**Issue by RCheesley** [mautic/Community-Portal#31]
When I go to meeting and then go to the registration section, and click on registration form as if I was wanting to edit the form,  I get a server error.

This is the ur that I landed on:

https://community.mautic.org/admin/assemblies/education-team/components/8/manage/meetings/25/registrations/form/edit

**Comment by froger** [comment]
Thanks for reporting, will have a look at the error. 

I guess we can not edit the form if it has been already answered once, but not sure, I am confirming.

**Comment by RCheesley** [comment]
This is becoming a problem as we need to be able to ask specific questions for our upcoming community sprint.

https://community.mautic.org/assemblies/community-team/f/5/meetings/79 - trying to add the form here, there are no registrations currently.

Hopefully will be fixed with the migration next week 🤞

**Comment by RCheesley** [comment]
This is throwing a bad gateway error still @froger (https://community.mautic.org/admin/assemblies/women-of-mautic/components/54/manage/meetings/103/registrations/edit > edit registration form) so guess it's not fixed yet by the latest update.

**Comment by RCheesley** [comment]
You have to save the form and the description first, and THEN you need to add the fields.
