### ISSUE TITLE
Pipeline to update Mautic

### ISSUE THREAD

**Issue by froger** [mautic/Community-Portal#52]
* [x] pipeline to update community.mautic.org with a manual action on a tag. 
* [x] pipeline to update a test instance manually (from `main`). 
* [x] update docker hub config (@RCheesley)

**Comment by RCheesley** [comment]
I've updated the Dockerhub so it now triggers on either pushes to main (which builds as latest) or pushes to tags.

**Comment by froger** [comment]
@RCheesley we have now a manual workflow, with two environments `Production` or `Development`. 
https://github.com/mautic/Community-Portal/actions/workflows/redeploy-dev.yml

When triggering the workflow, you will be ask in which environment you want to redeploy the docker image. 
The redeploy process takes around 2min, and the instance will be down for a 5min-ish duration. 


This has been tested on development. I can see now there is some issue on a fresh redeploy, that I am fixing right now. 


![Screenshot 2024-02-07 at 12 38 20](https://github.com/mautic/Community-Portal/assets/3929108/e14b04d9-8093-4acb-9813-8dda0265f6e0)


There is now issues on a fresh re-deploy, that I described here: #66, so my side you can close this issue 🎉🎉🎉

**Comment by RCheesley** [comment]
That's super awesome! Thanks for setting this up!
