### ISSUE TITLE
Saving Decidim Awesome scoped admins config results in bad gateway

### ISSUE THREAD

**Issue by RCheesley** [mautic/Community-Portal#72]
https://community.mautic.org/admin/decidim_awesome/config/admins I land here, then I get a bad gateway, when trying to add scoped admins.

**Comment by froger** [comment]
Thanks, I understand this block you for organizing GSoC. @rsdeus can you check this error?

**Comment by RCheesley** [comment]
Yeah it would be awesome to get this fixed as we need to enable the GSoC students to write their weekly update on the Community Portal and we plan to do that in the front-end.

**Comment by RCheesley** [comment]
@rsdeus @froger we're up against a time pressure here, GSoC starts on 1 May and we need to start onboarding our students. Are we any further forward with fixing this?

**Comment by rsdeus** [comment]
Hi @RCheesley, apologies for the delayed response.

We've identified the source of this issue and opened another issue with Awesome Decidim: [link to the issue.](https://github.com/decidim-ice/decidim-module-decidim_awesome/issues/296)

We also have a hotfix ready to implement, which requires restarting the application. We've scheduled this for midnight between 00:00 and 01:00 UK time. Could you please confirm if this timeframe works for you?

Thank you

**Comment by RCheesley** [comment]
Hey there, that's fine thanks - and thank you for digging into the issue.

**Comment by rsdeus** [comment]
Hi @RCheesley , we've completed the task and conducted testing. Could you please test it and validate the solution?
Thank you.

**Comment by RCheesley** [comment]
Thanks @rsdeus - I've just asked our GSoC students to check if they can do the scoped activities (add blogs and meetings) and will let you know once we confirm it's all good - but I was able to save the users in the field so tentatively it looks like it's resolved! Much appreciation!

**Comment by RCheesley** [comment]
While the bad gateway issue is resolved, the admins don't seem able to access the admin portal to add their blog posts:

When accessing /admin they get:

> it shows 'The page you're looking for can't be found. This address is incorrect or has been removed.'

**Comment by rsdeus** [comment]
Hi @RCheesley,
 
The feature is exhibiting some strange behaviors. However, I noticed that after I set my account to access the blog as an admin in the Decidim Awesome tab and then modified my account to a regular user, I was still able to access the blog component as an admin, but only through the assemblies. Additionally, I could only access the blog as an admin; the other tabs were not accessible.

Please check the video below to see how I was able to access the component. Also, please could you also check with the others to see if they can replicate this behavior?

https://github.com/mautic/Community-Portal/assets/8357006/3061497a-ed20-4496-8b65-3c46ac7e88eb

**Comment by RCheesley** [comment]
Thanks, I think this was a misunderstanding from the student - they are able to access it now so we should be good to go. So we can mark this one as done! ✅
