### ISSUE TITLE
Styling issue on login prompt

### ISSUE THREAD

**Issue by RCheesley** [mautic/Community-Portal#86]
[https://community.mautic.org/assemblies/general-assembly/f/71/](https://community.mautic.org/assemblies/general-assembly/f/71/)

This page could do with a bit of styling TLC, I think.

![screenshot-community mautic org-2024 08 22-13_25_34](https://github.com/user-attachments/assets/db0ce362-8ab1-45da-a09f-7a69c4a38177)

**Comment by chiragkhatri19** [comment]
Agreed and I would love to contribute in styling it!

**Comment by RCheesley** [comment]
Hi @chiragkhatri19 that'd be amazing!  Please check the readme for details on how to spin up a local instance in case you need it. Feel free to make a PR when you're ready and we can review it!

**Comment by Abhinav-Bansal751** [comment]
Hi @RCheesley i cloned the codebase and tried finding the file containing the button n prompt but couldnt find it.Could you pls help.

**Comment by RCheesley** [comment]
I have not looked in great detail but it seems like a good place to start looking might be _card.scss, and possibly _layout.scss?  cc @froger in case you can give any nudges here.

I'd suggest comparing the layout on this page to some of the other pages which have proper formatting/layout, and seeing what you can do to improve the layout on this page - being mindful that for example the card layout is most likely used elsewhere.

See if that helps you, and if not let us know and we can help with finding the right places to make the changes.

**Comment by froger** [comment]
Hi, for styling issues in general, it is probably linked to our custom theme.
To make it simpler, you can add css rules on Decidim Awesome: https://community.mautic.org/admin/decidim_awesome/config/styles

Once you have done the fix locally, I can review and add the css rule to the custom theme we have. 

Thanks,

**Comment by RCheesley** [comment]
@Abhinav-Bansal751 @chiragkhatri19 how are you getting on?

**Comment by Abhinav-Bansal751** [comment]
pls can u share the exact file where the code is written for this login prompt or button?

**Comment by Jaishree2310** [comment]
Hey @RCheesley , I would like to take this issue. Please assign it to me. 
Thank you!

**Comment by RCheesley** [comment]
@froger also could you check whether this one is resolved already? As we have some contributions keen to help with it if not.
