### ISSUE TITLE
Bad Gateway when trying to manage a form

### ISSUE THREAD

**Issue by RCheesley** [mautic/Community-Portal#89]
We have a new contributors form here:
https://community.mautic.org/processes/contribute-to-mautic/f/83/

When I try to manage the form, via the Process: https://community.mautic.org/admin/participatory_processes/contribute-to-mautic/components/83/manage/ I get a bad gateway error.

Given we don't get notifications when a form is completed, this is quite important, because I don't know if someone has filled out the form to request onboarding.

**Comment by rsdeus** [comment]
Hello @RCheesley,
We have identified the cause of this issue and already applied a hotfix, which is now in production without the need for a restart. Additionally, we've submitted a PR for the fix.
Thanks and best regards.
